name: multiple_random_choice
description:
  A function library to choose multiple items randomly. This library supports weighted randomly choosing too. Typical examples of usage are lottery and gacha.
version: 0.1.1
homepage: https://github.com/MenEnger/dart_multiple_random_choice
repository: https://github.com/MenEnger/dart_multiple_random_choice
issue_tracker: https://github.com/MenEnger/dart_multiple_random_choice/issues

environment:
  sdk: ">=2.15.0 <3.0.0"

dev_dependencies:
  test: ^1.19.5
  lints: ^1.0.1
